### ISSUE TITLE
Vue version required

### ISSUE THREAD

**Issue by pengbo37877** [smastrom/solid-collapse#1]
Is there a plan for vue version?

**Comment by smastrom-dolly** [comment]
Hi @pengbo37877, I never tought about making a Vue version. That's because I'm pretty sure something valid is already available in the great Vue ecosystem. In any case, I am going to take a deeper look and let you know.

**Comment by smastrom-dolly** [comment]
Hi @pengbo37877, sorry for getting back to you so late. I would like to inform you that I just released [vue-collapsed](https://github.com/smastrom/vue-collapsed). Have a nice weekend!

Simone
